spring:
  batch:
#    job:
#      enabled: false
    jdbc:
      initialize-schema: always
  data:
    mongodb:
      database: tweets
  neo4j:
    authentication:
      username: neo4j
      password: mminella1
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_batch
    username: 'root'
    password: 'p@ssw0rd'
  jpa:
    show-sql: true
    hibernate:
      naming:
        implicit-strategy: "org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl"
        physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
  sql:
    init:
      mode: never
      continue-on-error: true
      platform: mysql
