spring:
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: true
      name: transactionJob
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_batch
    username: 'root'
    password: 'p@ssw0rd'
  sql:
    init:
      mode: never
      continue-on-error: true
      platform: mysql

#logging:
#  level:
#    org:
#      springframework: DEBUG
